package com.skillport.protocol;

public enum MessageType {
    INSTALL_SKILL,
    INSTALL_PROGRESS,
    INSTALL_COMPLETED,
    INSTALL_FAILED,
    UNINSTALL_SKILL,
    UNINSTALL_PROGRESS,
    UNINSTALL_COMPLETED,
    UNINSTALL_FAILED,
    SCAN_TOOLS,
    TOOL_SCAN_RESULT,
    HEARTBEAT,
    HEARTBEAT_ACK
}
